name: Workflow

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 21.5.0

            - name: Install pnpm
              run: npm i -g pnpm

            - name: Install Dependencies
              run: pnpm i

            - name: Run e2e tests
              run: pnpm test:e2e

            - name: Run unit tests
              run: pnpm test:unit
